uphold/validator.js-asserts

- lib/asserts/uri-assert.js
- package.json
- test/asserts/uri-assert_test.js
Adds a URI assert by relying on the [URIjs](https://github.com/medialize/URI.js) library.
Also allows forcing the URI's protocol to match a configured value.
> Add URI assert

- lib/asserts/date-diff-greater-than-assert.js
- lib/asserts/date-diff-less-than-assert.js
- lib/asserts/null-or-date-assert.js
- lib/asserts/null-or-string-assert.js
- test/asserts/date-diff-greater-than-assert_test.js
- test/asserts/date-diff-less-than-assert_test.js
- test/asserts/null-or-date-assert_test.js
- test/asserts/null-or-string-assert_test.js
* Adds a `NullOrDate` assert.
* Fixes an issue with the `DateDiffGreaterThan` and `DateDiffLessThan` asserts that were incorrectly calling a dependent assert which was never properly initialized.
R=@ruimarinho
> Add null or date assert

- lib/asserts/country-assert.js
- lib/asserts/date-diff-greater-than-assert.js
- lib/asserts/date-diff-less-than-assert.js
- lib/asserts/equal-keys-assert.js
- lib/asserts/iso-3166-country-assert.js
- lib/asserts/not-empty-assert.js
- lib/asserts/plain-object-assert.js
- lib/asserts/uri-assert.js
- lib/asserts/us-state-assert.js
- package.json
npm@3 will no longer install `peerDependencies` automatically, which puts an end to package conflicts. We can now reliably trust this mechanism to avoid bloating this package.
This is semver-major, as peer dependencies must be resolved manually by the user.
> Move dependencies to peer dependencies

- README.md
- src/asserts/bank-identifier-code-assert.js
- test/asserts/bank-identifier-code-assert_test.js
- test/index_test.js
Adds an assert to test whether a value is a valid Bank Identifier Code (*BIC*) as defined in the [ISO-9362](http://www.iso.org/iso/home/store/catalogue_tc/catalogue_detail.htm?csnumber=60390) standard.
> Add Bank Identifier Code assert

- README.md
- package.json
- src/asserts/big-number-assert.js
- src/asserts/big-number-greater-than-assert.js
- src/asserts/big-number-greater-than-or-equal-to-assert.js
- src/asserts/big-number-less-than-assert.js
- src/asserts/big-number-less-than-or-equal-to-assert.js
- src/asserts/country-assert.js
- src/asserts/credit-card-assert.js
- src/asserts/date-diff-greater-than-assert.js
- src/asserts/date-diff-less-than-assert.js
- src/asserts/email-assert.js
- src/asserts/international-bank-account-number-assert.js
- src/asserts/iso-3166-country-assert.js
- src/asserts/uri-assert.js
- src/asserts/us-state-assert.js
With _npm 3.x_ peer dependencies are no longer installed automatically. This causes warnings like the following for our users:
```js
npm WARN EPEERINVALID validator.js-asserts@1.1.0 requires a peer of urijs@>=1 <2 but none was installed.
```
_Note that this is a warning, not an error._
There is no good way around this warning and I still think that "peerDependencies" is the best way to announce to other developers that this package includes "optional peer dependencies" (for the lack of a better term).
Since this module is now being transpiled from ES6 to ES5, we cannot simply wrap the `import` statements with a _try/catch_ so this PR simply reintroduces the `require` statement inside each exported assert function (because `import` can only be used at the top of the file).
If this PR is …
> Fix peer dependencies being required directly

- README.md
- src/asserts/equal-keys-assert.js
- test/asserts/equal-keys-assert_test.js
> Handle empty objects in `EqualKeys`

- README.md
- src/asserts/uri-assert.js
- test/asserts/uri-assert_test.js
This allows testing for specific types of URIs, e.g., `ip`, `domain`, `relative`, `absolute`, etc.
> Add support for the special `is` urijs constraint

- README.md
- src/asserts/date-assert.js
- test/asserts/date-assert_test.js
This PR adds a `format` option to the `DateAssert` that allows to check if a date is valid in a given format.
> Add format option to date assert

- src/asserts/date-assert.js
- test/asserts/date-assert_test.js
This PR removes the need for `format` to be a string in `DateAssert`.
As documented in [moment](http://momentjs.com/docs/#/parsing/special-formats/), the format can be a string, a array or a function. 
By having this limitation we can't support parsing a date with multiple formats such as ISO8601 or custom ones.
> Allow custom date formats

- src/asserts/date-diff-greater-than-or-equal-to-assert.js
- src/asserts/date-diff-less-than-or-equal-to-assert.js
- src/index.js
- test/asserts/date-diff-greater-than-or-equal-to-assert_test.js
- test/asserts/date-diff-less-than-or-equal-to-assert_test.js
- test/index_test.js
This PR adds two new date asserts for `less/greater than or equal to` that were missing.
> New date asserts

- index.html
This PR updates the URL for the `<script>` tag that imports `jQuery` changing the protocol from HTTP to HTTPs. This issue is currently preventing the `Flatdoc` from loading.
> Fix mixed content issue preventing page load

- package.json
- src/asserts/big-number-assert.js
- src/asserts/big-number-equal-to-assert.js
- src/asserts/big-number-greater-than-assert.js
- src/asserts/big-number-greater-than-or-equal-to-assert.js
- src/asserts/big-number-less-than-assert.js
- src/asserts/big-number-less-than-or-equal-to-assert.js
- test/asserts/big-number-assert_test.js
- test/asserts/big-number-equal-to-assert_test.js
- test/asserts/big-number-greater-than-assert_test.js
- test/asserts/big-number-greater-than-or-equal-to-assert_test.js
- test/asserts/big-number-less-than-assert_test.js
- test/asserts/big-number-less-than-or-equal-to-assert_test.js
`bignumber.js` version 7 introduced a breaking change:
> Only throw on an invalid BigNumber value if BigNumber.DEBUG is true. Return BigNumber NaN instead.
For projects that used the newer versions of `bignumber.js`, the assert `is.bigNumber()` and similar were not working when the input was invalid (internally the `new BigNumber()` was not throwing like before).
Version 6 also added the following breaking change:
> Rename methods: add is prefix to greaterThan, greaterThanOrEqualTo, lessThan and lessThanOrEqualTo.
This PR adds support for versions 7 and above.
It also adds support for an option `validateSignificantDigits ` flag, wich controls the behaviour of the validator when the input is a number with more than 15 significant digits.
- Before bignumber.js@7 and this PR:
```js
> new …
```
> Support bignumber.js@7+ and add optional `validateSignificantDigits` flag

- .travis.yml
- test/asserts/date-diff-greater-than-assert_test.js
- test/asserts/date-diff-greater-than-or-equal-to-assert_test.js
- test/asserts/date-diff-less-than-assert_test.js
- test/asserts/date-diff-less-than-or-equal-to-assert_test.js
Resolves https://github.com/uphold/validator.js-asserts/issues/175.
This PR also adds support for node 10 on travis, to enforce a passing build from now on.
> Fix date tests on node 10

- src/asserts/bank-identifier-code-assert.js
- test/asserts/bank-identifier-code-assert_test.js
This PR fixes an issue with the BIC assert to match the _ISO-20022_ definition present in _CustomerCreditTransferInitiationV03_ [XSD schema](https://www.iso20022.org/documents/messages/1_0_version/pain/schemas/pain.001.001.03.zip):
```xml
<xs:simpleType name="BICIdentifier">
<xs:restriction base="xs:string">
<xs:pattern value="[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}"/>
</xs:restriction>
</xs:simpleType>
```
Currently, `BICOLETO` is one example of an invalid BIC which is passing the assert.
We are also keeping the assert case insensitive.
> Fix Bank Identifier Code assert

- README.md
- src/asserts/callback-assert.js
- src/index.js
- test/asserts/callback-assert.test.js
- test/index_test.js
Add callback assert.
This assert adds more context to the callback error as suggested by @franciscocardoso.
When:
```
Assert.callback(() => {});
```
The error should be:
```
{
"__class__": "Callback",
"__parentClass__": "Assert"
}
```
Now when:
```
Assert.callback(() => {}, 'CustomClass');
```
```
{
"__class__": "CustomClass",
"__parentClass__": "Assert"
}
```
> Add callback assert

- src/asserts/callback-assert.js
- test/asserts/callback-assert.test.js
This PR prevents the usage of the Callback assert without a custom class that will improve the understanding of the raised errors.
[PLAT-517](https://uphold.atlassian.net/browse/PLAT-517)
- Every app that use callback without a custom error class.
Breaking changes so it is needed to increment the major version.
> Improve callback assert to ensure an error class

- package.json
- yarn.lock
This PR bumps the lodash version to `^4.17.21`.
This will allow to mitigate the [vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2021-23337) that affects the lodash version prior to `4.17.21`.
> Bump lodash@4.17.21

- src/asserts/aba-routing-number-assert.js
- src/asserts/big-number-assert.js
- src/asserts/big-number-equal-to-assert.js
- src/asserts/big-number-greater-than-assert.js
- src/asserts/big-number-greater-than-or-equal-to-assert.js
- src/asserts/big-number-less-than-assert.js
- src/asserts/big-number-less-than-or-equal-to-assert.js
- src/asserts/credit-card-assert.js
- src/asserts/date-assert.js
- src/asserts/date-diff-greater-than-assert.js
- src/asserts/date-diff-greater-than-or-equal-to-assert.js
- src/asserts/date-diff-less-than-assert.js
- src/asserts/date-diff-less-than-or-equal-to-assert.js
- src/asserts/email-assert.js
- src/asserts/international-bank-account-number-assert.js
- src/asserts/iso-3166-country-assert.js
- src/asserts/phone-assert.js
- src/asserts/taxpayer-identification-number-assert.js
- src/asserts/uk-modulus-checking-assert.js
- src/asserts/uri-assert.js
Pulls optional dependencies out of the initialization function, to improve performance for callers that use a particular assert multiple times, **achieving a 3x speedup** 🚀  (on my machine™)
I used the following script to benchmark the change:
```js
const _ = require('lodash');
const { Assert: BaseAssert } = require('validator.js');
const Benchmark = require('benchmark');
const BigNumberAssert = require('../src/asserts/big-number-assert');
const BigNumberAssertOld = require('../src/asserts/big-number-assert-old');
const Assert = BaseAssert.extend({
BigNumber: BigNumberAssert,
BigNumberOld: BigNumberAssertOld
});
const suite = new Benchmark.Suite();
suite
.add('BigNumber with implicit require (old)', function() {
Assert.bigNumberOld().validate(_.random(1, 10000));
})
.add('BigNumber with …
```
> Improve optional dependency performance

- package.json
- yarn.lock
There were a lot of deprecated and security fix dependencies that needed to be updated.
This leaves us with 6 moderate dependency issues, as opposed to ~70 moderate to severe.  The missing ones are due to `eslint`, which is a breaking change.
> Updates dev dependencies

- src/asserts/callback-assert.js
- test/asserts/callback-assert.test.js
I updated the test regex in the callback assert to allow custom error's with numbers, such as `CardNot3DSecure3DSEnabled`.
> Add support for numbers to be in callback assert custom class

- README.md
- src/asserts/null-or-assert.js
- src/index.js
- test/asserts/null-or-assert.test.js
- test/index.test.js
Resolves https://github.com/seegno/validator.js-asserts/issues/21.
Add a new assert to be used with other asserts to make them nullable. This way, we don't need to add new asserts like `NullOrUuid`, `NullOrIp`, and so on. And this also allows us to deprecate the asserts `NullOrDate` and `NullOrString` in the future.
With this new assert, if we want to check, for instance, a nullable foreign key in the UUID v4 format, we can do:
``` js
validator.validate(foreignKeyId, is.nullOr(is.uuid(4)));
```
The above example will return true is `foreignKeyId` is either null or passes the `is.uuid(4)` validation. If the validation fails, the returned validation error will include all information `is.uuid(4)` returns.
https://github.com/uphold/validator.js-asserts/pull/229 …
> Add `NullOrAssert`

- src/asserts/email-assert.js
- test/asserts/email-assert.test.js
Bypass email validation for deleted emails
https://uphold.atlassian.net/browse/BKO-5437
> Bypass email validation for deleted emails

- .github/workflows/release.yaml
- package.json
- test/asserts/taxpayer-identification-number-assert.test.js
- yarn.lock
- Update all dev dependencies.
- Update `@uphold/github-changelog-generator@4.0.2`
- Update `abavalidator@2.0.2`
- Update `bignumber.js@9.3.0`
- Update `creditcard@0.1.3`
- Update `curp@1.3.1`
- Update `google-libphonenumber@3.2.41`
- Update `moment@2.30.1`
- Update `release-it@19.0.3` and `release` workflow.
- Update `tin-validator@1.1.0`
- Update `validator.js@13.15.15`
> Update dev dependencies to fix vulnerabilities

- README.md
- package.json
- Move `validator.js` to dev and peer dependency.
- Update invalid `optionalPeerDependencies` to `peerDependencies` and `peerDependenciesMeta`. See the following for documentation on `peerDependenciesMeta`:
- `npm` https://docs.npmjs.com/cli/v11/configuring-npm/package-json#peerdependenciesmeta
- `yarn` `v1`/classic https://classic.yarnpkg.com/en/docs/package-json#toc-peerdependenciesmeta
- `yarn` `v4` https://yarnpkg.com/configuration/manifest#peerDependenciesMeta
- `pnpm` https://pnpm.io/next/package_json#peerdependenciesmetaoptional
> [!WARNING]
> This is a breaking change, so it should be part of a major release
> Fix `peerDependencies`
